### 端末を追加
POST http://localhost:5000/user/test-user/device/add
Content-Type: application/json

{
  "device": "OO:OO:OO:OO:OO:OO"
}

### ユーザーの端末一覧を取得
GET http://localhost:5000/user/test-user/device
Accept: application/json

### 登録された端末を検索
GET http://localhost:5000/bluetooth/scan
Accept: application/json

