### 端末を追加
POST http://localhost:5000/user/17a25b07-757f-4e7b-83af-4521c0a8a3aa/device/add
Content-Type: application/json

{
  "device": "OO:OO:OO:OO:OO:OO"
}

### ユーザーの端末一覧を取得
GET http://localhost:5000/user/17a25b07-757f-4e7b-83af-4521c0a8a3aa/device
Accept: application/json

### 登録された端末を検索
GET http://localhost:5000/bluetooth/scan
Accept: application/json

