### ユーザー一覧を取得
GET http://localhost:5000/users
Accept: application/json

### ユーザーを追加
POST http://localhost:5000/users/create
Content-Type: application/json

{
  "name": "山田太郎",
  "devices": [
    "40:B0:76:89:98:B4"
  ],
  "grade": "M4"
}

### ユーザー情報を編集
POST http://localhost:5000/users/edit/{{id}}
Content-Type: application/json

{
  "name": "山田花子",
  "devices": [],
  "grade": "M1"
}

### ユーザーを削除
DELETE http://localhost:5000/users/delete/{{id}}
Content-Type: application/json

### ユーザーの端末一覧を取得
GET http://localhost:5000/users/{{id}}/device
Accept: application/json

